# Generated by Django 3.2 on 2023-03-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230331_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'permissions': [('nfs_cliente', 'Pode visualizar as próprias notas fiscais como cliente')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='transportador',
            options={'ordering': ['nome'], 'permissions': [('nfs_transportador', 'Pode visualizar as próprias notas fiscais como transportador')], 'verbose_name': 'Transportador', 'verbose_name_plural': 'Transportadores'},
        ),
    ]
