# Generated by Django 3.2 on 2023-04-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data'], 'permissions': [('fazer_pedido', 'Pode criar um pedido')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
