# Generated by Django 3.2 on 2023-04-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='valor',
            field=models.IntegerField(default=10, verbose_name='Valor em pontos'),
            preserve_default=False,
        ),
    ]
