# Generated by Django 3.2 on 2023-04-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_beneficio_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficio',
            old_name='valor',
            new_name='pontos',
        ),
    ]
