# Generated by Django 3.2 on 2023-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_valor_beneficio_pontos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data'], 'permissions': [('fazer_pedido', 'Pode criar um pedido'), ('aprovar_pedido', 'Pode aprovar um pedido'), ('entregar_pedido', 'Pode entregar um pedido')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
