# Generated by Django 3.2 on 2023-11-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230615_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='transportador',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='produto',
            field=models.CharField(choices=[('Brita 1', 'Brita 1'), ('Brita 0', 'Brita 0'), ('Pó de pedra', 'Pó de pedra'), ('Brita corrida', 'Brita corrida'), ('BGS', 'BGS'), ('Brita 1/2', 'Brita 1/2'), ('Pedra rachão', 'Pedra rachão')], max_length=100, verbose_name='Produto'),
        ),
    ]
