# Generated by Django 3.2 on 2023-11-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20231107_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='transportador',
            name='bairro',
        ),
    ]
