# Generated by Django 3.2 on 2023-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20231107_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='transportador',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
    ]
