# Generated by Django 3.2 on 2023-11-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20231107_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Valor do Frete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Valor dos Produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.usuario'),
            preserve_default=False,
        ),
    ]
