# Generated by Django 3.2 on 2023-11-21 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231121_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaopontuacao',
            name='toneladas_por_ponto',
        ),
        migrations.AddField(
            model_name='configuracaopontuacao',
            name='reais_por_ponto',
            field=models.IntegerField(default=100, help_text='Quantos reais serão necessários para gerar 1 ponto pro cliente.', verbose_name='Reais por Ponto'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='transportador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.transportador', verbose_name='Transportador'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
